/**
 * This class is used to generate a predetermined label sequence for a compressed proof.
 * It is designed specifically for testing purposes, mainly to verify if it produces the same proof as mmj2.
 * The label sequence generated by this class is based on predetermined decisions.
 */

import { ILabelMapCreatorForCompressedProof } from './MmpCompressedProofCreator';

export class MmpHardcodedLabelSequenceCreator implements ILabelMapCreatorForCompressedProof {
	constructor(private labelSequence: string[]) {

	}
	createLabelMap() {
		const labelMap: Map<string, number> = new Map<string, number>();
		this.labelSequence.forEach((label: string) => {
			const nextIndex: number = labelMap.size + 1;
			labelMap.set(label, nextIndex);
		});
		return labelMap;
	}
}