import { Range } from 'vscode-languageserver';
import { MmToken } from '../grammar/MmLexer';
import { InternalNode } from '../grammar/ParseNode';
import { concatWithSpaces, rebuildOriginalStringFromTokens } from '../mm/Utils';

export interface IMmpStatement {
	toText(): string
}

export interface IMmpStatementWithRange extends IMmpStatement {
	range: Range
}

export class MmpTheoremLabel implements IMmpStatement {
	dollarStatementKeyword: MmToken;
	theoremLabel?: MmToken;

	constructor(dollarStatementKeyword: MmToken, theoremLabel?: MmToken) {
		this.dollarStatementKeyword = dollarStatementKeyword;
		this.theoremLabel = theoremLabel;
	}

	toText() {
		const label: string = ( this.theoremLabel != undefined ? this.theoremLabel?.value : "example" );
		const text: string = this.dollarStatementKeyword.value + " " + label;
		return text;
	}
}

export class MmpComment implements IMmpStatement {
	/** comment tokens, exclued the startin '*' character */
	contentTokens: MmToken[]
	comment: string;

	constructor(contentTokens: MmToken[], comment: string) {
		this.contentTokens = contentTokens;
		this.comment = comment;
	}

	toText() {
		return this.comment;
	}
}


export type UProofStatementStep = {
	label: string,
	parseNode: InternalNode;
}



export class UProofStatement implements IMmpStatement {
	proof: UProofStatementStep[];
	constructor(proof: UProofStatementStep[]) {
		this.proof = proof;
	}

	//#region toText
	toText(): string {
		// let text: string;
		// if (this.proofMode == ProofMode.normal) {
		const labels: string[] = [];
		this.proof.forEach((uProofStatementStep: UProofStatementStep) => {
			labels.push(uProofStatementStep.label);
		});
		const labelsString = concatWithSpaces(labels);
		const text = "\n$=    " + labelsString + " $.";
		// } else {			// this.proofMode == ProofMode.compressed
		// 	text = "***???**";
		// 	throw new Error("Return compressed proof. Not implemented yet!");
		// }
		return text;
	}
	//#endregion toText
}

/**
 * a IUStatement that represents the text for a proof statement (generated by
 * the unification process); it has to be removed by a subsequent unification process
 */
export class TextForProofStatement implements IMmpStatement {
	statementTokens: MmToken[];
	constructor(statementTokens: MmToken[]) {
		this.statementTokens = statementTokens;
	}

	//#region toText
	toText(): string {
		const text = rebuildOriginalStringFromTokens(this.statementTokens);
		return text;
	}
	//#endregion toText
}

// export type UStatement = UTheoremLabel | UProofStep | UComment | DisjVarUStatement | UProofStatement | UCompressedProofStatement